version: "2.4"
services:
  base:
    image: node:10
    volumes:
      - .:/app
      - .docker/node_modules:/app/node_modules
    working_dir: /app
    env_file:
      - ./.env

  install:
    extends:
      service: base
    command: yarn

  server-src-build:
    extends:
      service: base
    command: yarn server:src:build

  db-migrate-reset:
    extends:
      service: base
    command: yarn db:migrate reset
  db-migrate-migrate:
    extends:
      service: base
    command: yarn db:migrate migrate
