version: "2.4"
services:
  base:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../graphile-starter-app:/app
      - node_modules-volume:/app/node_modules
    working_dir: /app
    environment:
      - DOCKER_MODE
      - DATABASE_HOST
      - DATABASE_OWNER

  node-install:
    extends:
      service: base
    command: yarn

  server-src-build:
    extends:
      service: base
    command: yarn server:src:build

  db-migrate-reset:
    extends:
      service: base
    command: yarn db:migrate reset
  db-migrate-migrate:
    extends:
      service: base
    command: yarn db:migrate migrate

networks:
  default:
    name: graphile-starter

volumes:
  node_modules-volume:
